import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "@/components/AuthProvider";
import Navbar from "../components/Navbar";
import Clouds from "@/components/Cloud";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex flex-col">
            <Navbar />
            <main>
              <div className=" bg-rose-700 fixed inset-0 -z-10 flex gap-4 overflow-hidden opacity-20">
                <Clouds />
              </div>
              {children}
            </main>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
